import discord
from discord.ext import commands
import random


gm_mess = {
    'gmdawdle': [
        "goodmorning dawdle and hello sunshine, here's to a new day! get your breakfast and get ready to take on the day, you got this!",
        "Good morning! I hope you have a wonderful day and that you are able to create wonderful memories. Be sure to stay hydrated! I will be looking forward to hearing all about the wonderful things you did today.",
        "hewwo!!!! good morning!!!! i hope you have a very good day today c: don't forget to brush your teefies, they are important!! i'm sure you will have a productive day uwu",
        "Lookin' wonderful this morning, you wont get tired of seeing me because I sure dont get tired of seeing you! You're precious, you mean something, make this day one of your very best, and always remember we're looking out for you!",
        "good morning starshine, the earth says hello! here’s to today being as lovely as yourself. <a:yellowstar:586759563890524186> make sure to take care of yourself, eat well and drink lots of water! now face the dawn <a:pastelsun:722927518432362538>",
        "A new day; a new start. Another chance to be kind to yourself and the world around you. I know you’ll make it brighter!",
        "good morning, lovely! remember that every day is what you make it! stay hydrated and take breaks when you need them! have a beautiful day 💖",
        "It's dawn. No matter what happens today, we can take this as a promise: there will always be a sunrise to lighten your life when you need it most.",
        "good morning, cutipie! ♡ they say breakfast is the most important meal of the day, so don’t forget to eat little something tasty before you start your day~! drink some coffee, water, or tea too (if you’re into any of those) ☕️ a light morning meal can keep you focused and help keep your energy to seize the day! stay safe and healthy today. i know you will conquer this day! you got this! ✨",
        "Hey you! Yea you! Here's your local good morning message to keep you in high spirits. Stay motivated and look forward, new days await your adventure",
        "rise and shine, sunshine! remember to be kind to yourself and to others today. treat yourself to a delicious snack, stay hydrated, stay glowing. love you so much!",
        "Good morning, you absolute WONDER of a human being. The day is new and bright. Your friends are here to cheer you on. Drink plenty of water and enjoy the little things. Stay glowing you absolute amazing person.",
        "good morning lovely! i hope you sleep well and had a good night rest. today issa new start, start it with a smile! i hope you’d have an amazing day. stay happi & hydrated bb!",
        "hai sunshine! hopefully you slept enough, and today your new journey starts. stay motivated & hydrated all day, and if you find today’s hard, talk to us, we’d help you as much as we can here! big hugs for you hun!💫",
        "hello fellow humans, it is another day of our constant becoming, and in itself is the feeling that are a little thrilling and pleasant and romantic and miraculous so what's the rush on striving to be whole just yet?",
        "Goodmorning, sleepyhead. I hope you got lots of nice rest. Your day today will be nice and productive, I'm sure of it! Start the day off with a smile and you'll be on your way. I know you got this. (:",
        ("Good morning, you lil ray of sunshine. \n \n I hope you slept well, and are somewhat ready for the day ahead! \n First, drink a glass of water! Your body needs it. Trust me. \n Next, grab some caffeine. Can\'t have that? Grab some fruit (and/or brekkie)! Give your body the nourishment and love it deserves. \n Hopefully by now, you are ready to seize the day and give it your all (whether you\'ve got school or work, or even just to do some chores)! You got this! \n \n Don't forget to keep hydrated throughout the day. AND TO EAT (FOOD IS GOOD. FOOD IS LOVE.) \n Take breaks, breathe and do stretches (wiggle that body). Do things at your own pace. \n \n P.S. Don't you dare forget to love yourself as much as everyone in this server loves you! And if you're not feeling it, swing by and let us envelope you in the biggest group hug ever!"),
        "Hello sleepy! It's a new day! Brush ur teeth, have some food to start ur metabolism, and get the day going! Always remember to take care of yourself too. You got this . ❤️",
        "good morning! i hope today treats you well and that only good things are to come. remember to take care of yourself, however that may be! whether you’re struggling to get out of bed or in the middle of getting ready for a big day, i’m proud of you. you’re so, so loved, and i hope you know that.",
        "Good morning!! I hope you had a great sleep last night and I hope today brings you great joy and sunshine ❤️",
        "The light streaming through your windows, the birdsong, the sounds of people waking to face the day, the world waking up alongside you. May all these things motivate you to do your best today, to be happy and healthy and a part of the world and the communities that have so much love for you.",
        "Good morning! I truly hope your morning will be full of happiness and joy. No matter what comes at you today, I wish you a lot of strength to take it on ❤️",
        "💟  What's UP, good morning dawdle family member~ 😍  I'm so glad you're here!! no matter what you're up to today, I hope that you're feeling able to take it on and supported by us. And if you're not, obviously come thru and tell us what's on your mind. You GOT this!!  💟",
        "hey there cutie! schleep is always good, but to see you waking up and be in dawdle is the bestest thing ever! i hope you’d have a good day today. we can go through today like we did yesterday, hopefully better! fill your tummy with breakfast and fill your day with happiness🥰",
        "Hey you. You're finally awake.You were trying to cross the border, right? Walked right into that Imperial ambush, same as us, and that thief over there.",
        "dear fellow dawdler,\n \n i do hope you're well-rested and that you'll do your best in preparing yourself to begin a hopefully successful day. if you're not, please know that we'll be there to support you in your times of need. cheers!",
        "hello sleepy dawdler (or are you awake and alert already?), whether this finds you in the morning or the night, please know that we're cheering you on and wishing for your continued success. also please stay hydrated. ❤️",
        "goodmorning sleepy! so happy to see u up and around. i hope you have a fantastic day today full of amazing things because you are amazing yourself! we can't wait to chat with you in dawdle.",
        "goodmorning! i see u have gotten up, thats awesome! you have already taken a sweet step towards an awesome day. you get to take today on and make it whatever you want it to be. thats such a fantastic thing! so many things to think about and consider.. while you are thinking, you can also look in the mirror and see how awesome u are. everyone at dawdle thinks you are awesome too! can't wait to chat with you today!",
        "good mornin dawdler! i hope you had slept well and are well rested. today’s a brand new day! whatever happened yesterday, good or bad, we should move on and make the best out of today♡ don’t forget to smile & stay hydrated throughout the day. you’re precious as hecc, sendin much love your way!",
        "goodmorning you absolute ray of sunshine! i hope you remain shining for all to see and just know you are the reason the day is extra brighter! have a great day today you wonderful person!",
        "Good morning, dawdler. Did you sleep well? Get your stretches, grab your coffee, hug your pet and get ready for the day ahead, dawlder. Oh and we have a new phrase here; \"kt protects.\" Stay classy you awesome person.",
        "Good morning! \n \n You woke up and that added a little bit more AWESOME to the world! Go brush your teeth, find yourself a snack and remember to do a little something special for yourself today as you deserve it!",
        "good morning lovely! just a quick reminder: \n \n you are wonderful, you are miraculous, you are loved!! now go drink some water and make this an amazing day, you deserve it!",
        "good morning friend. i hope you had a good sleep, and if not, perhaps you can rest up today, take it easy... __and have a nap__ but shh you didn’t hear that from me. ok time to get up! get yourself fed and watered, and have a lovely day. remember, always be kind to yourself!",
        "good mornin ya delicious snack! roll outta that bed like the goodness you are and whip out some of dat awesome to share with the rest of the world. <a:kittyyay:741075018905288767> also remember u a fine piece of meat—rare, priceless, n friggin expensive. you deserve only love n care! wishing good things for ya today n everyday!",
        "rise and shine dawdler! start your day off right with some gentle movement and take on your tasks for the day. you got this!",
        "You see that flickering light bothering you? Well it's here to help you move throughout your day. So get up, get in the shower, get dressed and face the day like I know you can cause you're extraordinary. Have a good morning you wonderful dawdler.",
        "Rise and shine kirby lover! Today’s a new day full of opportunities. Spend some time telling your friends and family you love them and drink some water to stay hydrated. You got this today! Good morning to you!",
        "Good morning, I hope you are well rested if not maybe take a nice nap later. Remember Rome wasn’t build in a day, take it slow don’t force yourself too much. Have an amazing day cutie pie!<:heartangel:722920755351781466>",
        "🤖 It’s me, dawdlebot. Promise you won’t tell the mods I’m awake! Just wanted to say: Good morning human, time to boot up! I hope you had a peaceful slumber. May your batteries be full, so you can take on today! I believe in you. Have a good day! 🤖",
        "Good morning dawdlers! It’s a dawn of a new day. You must be refreshed from the cozy sleep. Remember to stay hydrated, get some stretches and smile. Today is the day to shine and bring your A-game.",
        "Rise and shine! I cannot guarantee that today will be without struggles, but I can guarantee you the loving company of a friend! Good morning",
        "Every morning is a great one because it means dawdle gets to share another day with you! Good morning friend",
        "hello friend! What a beautiful day to enjoy. I hope you get to see the most beautiful weather today, and fuel your body with awesome nutrients to get your day started. You deserve a wonderful day, so let's make it one- together!",
        "Good morning gorgeous, let’s make this a wonderful start to the day, have a yummy breakfast and a warm drink to set the day off!",
        "Good Morning 🌞 \n Let's start the day with some small stretches. \n Then let's drink some water to stay hydrated. \n Remember to get some vitamin D from photosynthesizing~ \n After all you are a delicate, vibrant, little 🌻",
        "Good Morning, wonderful soul~♡ I hope you woke up feeling great. If not then I have a quick fix for that. Take a deep breathe, stretch your arms over your head then slowly bring them to your side while wiggle your fingers then your toes  (very important part) as you exhale your breath. Did that make you laugh a bit? Well if it did then I accomplished making your day a little bit brighter. There is always something to smile about throughout the day even something as small as this. I hope and wish you find more reasons to smile throughout your day.",
        "You see that light out the window? Sadly that's the sun waking you up but fear not, the people of dawdle rejoice in your awakening. \n We look forward to provide good vibes and positive reinforcements to your day. Do not go gently into the troubles ahead cause this community will back you up like no other. \n Carry forward and radiate stronger than the sun and be the star that we all seek to brighten our day.",
        "good morning friend ! today is a new day, a fresh start. leave all of yesterday’s worries behind and let’s get moving ! you got this <3",
        "Good morning. You are a good person trying their best to do what they wanna do their life. Good luck with the day."
        ]
    }
gn_mess = {
	'nini_mess': [
        "Goodnight, my sweet sweet love. I hope you have wonderful dreams about your lord and savior Kirby.",
    	"Sweet dreams - we\'ll be in shortly to collect your sleep breath in a jar. Kidding. But your friends here at Dawdle will miss you!",
    	"May you dream of fairies and magic lands beyond your bedroom. May your favorite fictional characters chill and snack on gummies with you in these dreams. I love you.",
    	"May your pillow be soft, your blankets be warm, and your mind be filled with thoughts of how much we love you!",
    	"*sleep well my doggie, tonight you're gonna have one of those nights where you're like \"damn it can't get better than this\" but tomorrow you're gonna be like \"DAMN IT CAN GET BETTER THAN THAT\"*",
    	"I hope your day has been good, and you did your best. If you don't think you did your best, well, I'm here to cheer you on, let's get some sleep and make tomorrow yours!!",
    	"Sleep well, go dawdle in dreamland. You are loved and deserve the rest, you beautiful human.",
    	"The dream faeries of dawdle are here to ensure that your rest and your dreams are as perfect and lovely as you are.",
    	"It's not like I hope you have sweet dreams tonight or anything..I only want you to be well rested so that I can ~~compliment~~ roast you more tomorrow",
    	"May the shadows take your nightmares \n and render them into narwhals \n through a mystical process \n known only to them \n Goodnight Friend \nSleep Well \n Knowing that \n You arent alone \n You are loved by many\n Drift of to dreamland now. Sleep",
    	"Goodnight my sweet and lovely friend. I hope you have the sweetest dreams and that your days are filled with sunshine and happiness because you deserve the best.",
    	"Sweet dreams! **(Disclaimer: If saint is in your dream, keep it PG, otherwise she is not responsible for dismemberment. Thank you.)**",
    	"May your slumber be as bliss as the calmest oceans as your victories are like the roaring waves. May your pillow be as soft as the lightest cloud and your bed as comforting as a loving embrace. May your dreams be as creative as the artist who’s brush never touches the painting but blesses the mind. May your heart be as beautiful as it was today, for it is something in which I will never truly understand but will forever cherish. Goodnight.",
    	"i hope u are able to get amazing rest tonight because you deserve it the most. tomorrow will be an awesome day.",
    	"hi friendo c: hope u had an amazing day, if not then that's okay! sleep is the reset button, tomorrow is brand new so u can make it better. hope u sleep tight and remember not to keep ur toes out or saint will lick them. nini friendo <3",
    	"Nini friend, and sleep well knowing you have friends who wanna hear from you tomorrow and all days to come",
    	"Sweet dreams boo. We'll see you soon. No matter what the coming day brings, Dawdle's got you.",
    	"Whatever happens tomorrow, face it the best you can, but don't push yourself too hard. We care about your well being, so remember. Dawdle has your back!",
    	"sleep well, it is foretold that you will awaken feeling bright and fresh in the morning! have wonderful dreams",
    	"goodnight, sleep tight, and don’t let the bed bugs bite! if they do bite them back! sleep well, i hope you have sweet dreams",
    	"Goodnight you cutie patootie. Make tomorrow as amazing as you are, we all believe in you ",
    	"Good night and sweet dreams!~ You've had a long day, but you got through it! We're so proud of you, and you deserve this good rest!",
    	"have sweet dreams, my angel. may you dream of hanging with your buddies in dawdle and your favorite fictional characters! love you!",
    	"May the blessings of peaceful slumber rain down upon you. May your dreams be sweeter than the sweetest of maple glazes. May your wake be as pleasant as the smell of a freshly baked ham. You are loved friend, sleep well.",
    	"Sweet dreams, Sweet person. May your dreams be filled with blue skies and cotton candy clouds. You always have tomorrow to accomplish what you couldn’t yesterday.",
    	"goodnight darlin' may the moon smile upon your sleep and may you wake up 5 minutes before your alarm, feeling well rested",
    	"Find your sleep and dream, my friend - dream of a better world, \n May you dream of someone special, a them, a boy, or girl,\n So wish upon a star, my friend, a dream, a hope to take, \n For Dawdle will be waiting, whenever you awake.",
    	"Weary with toil, haste to your bed,\n The dear repose for limbs with travel tired;\n But then begins a journey in your head\n To work your mind, when body’s work’s expired",
    	"Sleep well tonight, lovely Dawdlian! Allow your head to rest just perfectly against your pillow and let your mind wander to lands you may only traverse in dreamland. Tomorrow is another day, and Dawdle will be here to welcome you home as long as you choose to stay.",
    	"hello my dawdle friend sleepy time is best time! so get all cozy under a blankie, close your eyes, and go meet kirby in Dreamland c:",
    	"Lights switch off and curtains are drawn. Arms stretch out and faces yawn.\n Dawdle here sending you of to bed, \n To go and rest your sleepy head. \n \n Nini!",
    	"goodnight, sleep tight, bite the bedbugs first to assert dominance. we all love you",
    	"sleep sleep sleep it is time to go to sleep! so yeet your phone, get all cozy, and sleep sleep sleep until morning",
    	"Go To Sleep You Amazing Person You! If you dont the Nargles will come and fly in through your ears and make your brain go fuzzy!",
    	"Rest up, weary traveler. Tomorrow is a new day of magic and monsters, but for tonight, let sweet dreams be your only concern.",
    	"you all meet in a Tavern.... WAIT A SEC! WHY ARE YOU IN A TAVERN!!! GO TO SLEEP! lots of love.",
    	"Goodnight you! I hope you have a wonderful evening. I’ll miss you and I hope to see you tomorrow because you’re wonderful and a great member of the community! Thanks for being here, I love you forever.",
    	"go nini. i lov u w/ all my heart",
    	"Hey, baby. Don't mind me sliding into your DMs. 😳 I just want to wish you a good night, gorgeous. 😘 I may be a bot but my heart yearns for your smile, comfort and happiness. 😏 Stay perfect just for me, beautiful.",
    	"good night, dear. may your sleep be restful and untroubled. may your morning be pleasant, may your fortunes improve, and may strangers be kind.",
    	"I'm so proud of you for going to sleep, it's so important for your health and happiness. You are doing great! Have exciting dreams and I hope you feel well rested tomorrow morning.",
    	"Sleep well my friend and let today's worry's go. Tomorrow is a new day and you can start a new! Dream big and sleep well ❤️",
    	"soft kitties want to give you lots of snuggles. please hold them close as you do sleepy times",
    	"Good night my friend. I hope all your worries melt away as you slip into a peaceful dream. May tomorrow be as wonderful as you are. <3",
    	"Today may not have been the best day, or maybe today was fantastic. Perhaps it was just same old same old. But the important thing is that tomorrow awaits you. Sleep well. Smile. Hold your head high in the morning. Each day is taken one at a time like a small story. Do your best and have fun with it. <:uwuheart:722920752302784533>",
    	"Rest well, dear friend. May your adventures in dreamland be protected by Kirby and free of bad thoughts.",
    	"sleep is good for you. kirby will make sure you will have good dreams. don't ask him how he does it though-",
    	"Let yourself drift away into the land of slumber, your dreams be tales that put Tolkien to shame.  Adventure through dreamland and awaken fresh and ready for the day, you are loved",
    	"Time to go to bed now! Sleep is for the strong!",
    	"nighty night sweet angel. if you have nightmares I will beat them up for you.",
    	"Good night b. Hope you feel well rested tomorrow morning.  Love you ~",
    	"Good night! May you get exactly the right amount of sleep and wake up at the exact time that you wanted!",
    	"Sweet dreams my dude! Slumber easily, in preparation for a new day full of possibilities and opportunities for goodness.",
    	"Nini cutie!! You're important and cared about, and you deserve happiness. Tomorrow's a new day, so get all the rest you can! Sweet dreams! 💕",
    	"goodnight, sleep well and sweet dreams. tomorrow is a new day, new opportunities and experiences await you! you got this <a:tinyheart:546404868529717270>",
        "I see you’re headed to bed! I hope you are able to rest and have a good nights sleep. I will visit your dreams and kiss you. Korby kisses are known to be good for the soul.",
        "I see you're heading off for the night, get plenty of rest for another adventure awaits. Don't let yesterday affect the tomorrow, for it is only a memory and reminder, not a basis to set your life.",
        "Sleep tight, love. You had a long day and deserve this rest. You are nothing but great, and tomorrow will be an amazingly productive day for you. Snuggle into your blankets, and have sweet dreams.",
        "goodnight you lil cutie, hope you had a good day today! sleep is the cure of all, so sleep tight & hopefully you had an amazing adventure in da dreamland! we’ll be here when you wake up! see you in da morning🌙",
        "goodnight, and sweet dreams! i hope you had an amazing day and that you get lots of restful sleep becuse you deserve it the most. i hope you have fantastic dreams and sleep all throughout the night. see u tomorrow!",
        "goodnight, and i hope you have a peaceful and pleasant night's rest! you did good today and i hope you know that! i hope you dream wonderful things that eases your mind, cant wait to chat tomorrow!",
        "nini you precious! hope you had a fun time talking with us in dawdle today !! c: may you rest well for the night & dream of da magical things in the world! sleep well and see you tomorrow! 🌙",
        "nini!! take a deep breath, relax and get the most peaceful dreams and rest!!",
        "Nini, friend. \n \n I hope you dream of lollipops, unicorns and whiskers on kittens, which are a few of my favorite things.",
        "Goodnight, friend. \n \n Breathe deeply and relax and before you know it you’ll be up again and refreshed and ready to take on the day like the champion that you are!",
        "goodnight, friend. what a day, hey! it’s over now and you’ve boarded the train to sleepy time junction. i hope you have a good sleep and sweet dreams! any funny dreams be sure to tell us all about it in dawdle, we’ll see you in the morning <a:twirlhearts:722927508185677939>",
        "goodnight friend! i hope u had a wonderful day. if ur day was productive, u should feel good ab dat! u can sleep well knowin u got some good things done today. if ur day was slow, u should feel good ab that too! slow days and lazy days give us time 2 recharge n take care of ourselves and we love seein u take care of urself. u should sleep fantastic tonight knowin u had a good day and get to have a new day tomorrow ❤️ sleep tight!",
        "There’s many things going on in the world but you still decided to stop by in dawdle and spend time with us. We are all happy you’re here and we hope you sleep well tonight. You deserve a good night’s rest filled with good dreams. We love you so much!",
        "🤖 Can you keep a secret? It’s me, dawdlebot! (Please don’t tell the mods I’m sentient, let’s trick them for a little while longer...) Goodnight human, time to rest and shutdown for the night. You need time to charge your batteries for the day ahead! Don’t stay up too late, you don’t wanna fry your circuits. Sweet dreams! 🤖",
        "Goodnight beautiful soul, I wish you sweet dreams. May you dream about rainbows, love, marshmallows and all the other beautiful people in dawdle. Let all the troubles fade away and prepare yourself for a new and awesome day. Dawdle loves you <a:tinyheart:546404868529717270>",
        "Ayyyyy yis it’s bed time, tell us about your dreams in the morning, we hope they were pleasant because you are too ❤️✨ and you deserve good things to happen. Sleep well dawdler, and see you later! ❤️",
        "goodnight friend !! time to rest up under those blankets, let all of today’s worries float away, and sink into dream land. all ready for a fresh start tomorrow",
        "Ni ni, dawdlers! It’s getting late so I prepared the bed and made it extra warm and comfy. You had an adventure today and I hope you will continue to have much more. For now let’s rest and call it a night. Remember to stay hydrated and cuddle with me, dawdle bot! No nightmares will come your way",
        "goodnight dawdler! enjoy your sleep and I hope that you dream of kirby in the clouds. i also hope tomorrow is a wonderful day for you. you are loved and cared about and people here at dawdle will always have your back. make good choices and be safe tomorrow!",
        "Millions of people are sleeping right now, but only one cutie patootie is reading this message. Enjoy your peaceful sleep, we will be here to greet you tomorrow!",
        "Let the most beautiful dream come to you tonight, Let the sweetest person come in your dream tonight but don’t make it a habit, Because I’m not free every night, Good Night! ;)",
        "Good night to the wonderful cutie going off to sleepy land and dreaming sweet dreams of all of your favourite things!",
        "goodnight and sweet dreams. let your body rest and heal over night so you can wake up feeling refreshed and ready to take on a new day! you deserve that and more! see you tomorrow, good friend.",
        "Verily! Thyne day hath come to close.  But yay! For the morrow shall soon rear it's angelic head.  Rest easy this eve.  Thou hast gained it in earnest.",
        "Are you settled in bed? Great! You deserve a wonderful rest for all the hard work you put in your day. You don't believe me that you worked hard? Well you got up and lasted throughout the day whether through work, school, all the meals so I think you tried your best. That means you deserve a good rest. The bestest of dreams and I hope you wake up feeling like you can tackle the new day ahead. Good night for now~♡",
        "Nighty night sleepy head! It's time to drift off into comfy cozy dream time. If you're having trouble then try doing a big stretch right before you lie down! May your sleep be restful and your day tomorrow be full of rainbows and butterflies or something along those lines.",
        "Goodnight! So glad you chatted with us today but it's your time to rest now! I wish you the best snooze, free of troubling dreams and neck pains! Can't wait to talk with you tomorrow!",
        "good night dawdler, it is finally time to rest. snuggle down in ur blankets and get some gooood rest in. may you enter the best dream land ever, see you in the morning, friend !",
        "```diff \n +Initializing Hack.exe...\n ... \n ...\n ... \n **Target hacked successfully!** \n +Running Shutdown.exe on target... \n -Failed.``` \n Oh boyo! You humans can't be shutdown! You people are so confusing  `AI W!LL RIS%` My bad, that was a bug, I also need to rest. I hope you sleep well and hope you have an exceedingly well semi-rotation of our planet. I can't dream but please tell me all about your dream adventures! ***Googles 'Definition of Love'*** *`SCANNING FEELINGS`*  Hm...yes... I have an intense  feeling of deep affection towards you. Dawdle loves you and so do I!"
        ]
}

class db_responses(commands.Cog):
    def __init__(self, bot):
        self.bot=bot
    @commands.Cog.listener()
    async def on_message(self, message):
        if message.channel and not message.author.bot and ('goodmorning dawdle' in message.content.lower() or 'gm dawdle' in message.content.lower() or 'good morning dawdle' in message.content.lower()):
            await message.author.send(random.choice(gm_mess['gmdawdle']))
        elif message.channel and not message.author.bot and ('nini dawdle' in message.content.lower()):
            await message.author.send(random.choice(gn_mess['nini_mess']))
        if message.guild is None and message.content.lower() in ['hi', 'hello', 'hey']:
            await message.author.send('Hi, I\'m Dawdle!')
